/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frontend;

import java.awt.Color;
import javax.swing.BorderFactory;
import Backend.*;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import javax.swing.*;
import com.google.gson.*;
import javax.swing.table.TableModel;

/**
 *
 * @author aqibm
 */
public class ResultManagement extends javax.swing.JFrame {

    /**
     * Creates new form Students
     */
    ArrayList<ClassBean> allclasses = new ArrayList<>();
    ArrayList<SectionBean> allsections = new ArrayList<>();
    ArrayList<StudentBean> allStudents = new ArrayList<>();
    ArrayList<SubjectBean> allsubject = new ArrayList<>();
    ClassBean classes = new ClassBean();
    SectionBean sections = new SectionBean();
    StudentBean students = new StudentBean();
    SubjectBean subjectBean = new SubjectBean();
//    JTextField[] subjectmarksinput;
//    JTextField[] subjectmarksoutof;
    ArrayList<JTextField> subjectmarksinput = new ArrayList<>();
    ArrayList<JTextField> subjectmarksoutof = new ArrayList<>();
    Database db = new Database();
    int j;
    public ResultManagement() {
        initComponents();
        setLocationRelativeTo(null);
        allclasses = classes.getAllClasses();
        int classid;
        for(int i =0;i<allclasses.size();i++){
            classes = allclasses.get(i);
            class_selection.addItem(classes.getClassName());
        }
        DefaultTableModel model = (DefaultTableModel)allstudentsbysection.getModel();
        Object[] rowData = new Object[4];
        for(int i=0;i<model.getRowCount();i++){
            model.removeRow(i);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        exit = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        addresult = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        section_selection = new javax.swing.JComboBox();
        class_selection = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        allstudentsbysection = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(255, 102, 51));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        exit.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        exit.setForeground(new java.awt.Color(255, 255, 255));
        exit.setText("X");
        exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitMouseClicked(evt);
            }
        });
        jPanel2.add(exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(838, 0, 22, -1));

        jLabel15.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Result Management ");
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 40, -1, -1));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/images/reportcard_icon_48px_white.png"))); // NOI18N
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 60, 60));

        jLabel14.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/images/back.png"))); // NOI18N
        jLabel14.setText("Back");
        jLabel14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel14MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 40, -1, -1));

        jLabel1.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel1.setText("Select Section");

        addresult.setBackground(new java.awt.Color(255, 102, 51));
        addresult.setForeground(new java.awt.Color(255, 255, 255));
        addresult.setText("ADD");
        addresult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addresultActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(255, 102, 51));
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("View");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(255, 102, 51));
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("DELETE");

        section_selection.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                section_selectionMouseReleased(evt);
            }
        });
        section_selection.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                section_selectionActionPerformed(evt);
            }
        });

        class_selection.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                class_selectionActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel6.setText("Select Class");

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 380, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 286, Short.MAX_VALUE)
        );

        allstudentsbysection.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Student Id", "First Name", "Last Name", "Father Name"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(allstudentsbysection);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(class_selection, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(section_selection, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(addresult, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(8, 8, 8)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(class_selection, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(section_selection, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(addresult, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(47, 47, 47))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void class_selectionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_class_selectionActionPerformed
        // TODO add your handling code here:
        section_selection.removeAllItems();
        jPanel3.removeAll();
        jPanel3.revalidate();
        jPanel3.repaint();
        jPanel3.removeAll();
        subjectmarksinput.clear();
        subjectmarksoutof.clear();
        int index = class_selection.getSelectedIndex();
        classes = allclasses.get(index);
        allsections = sections.allSectionsByClass(classes.getClassID());
        for(int i=0;i<allsections.size();i++){
            sections = allsections.get(i);
            section_selection.addItem(sections.getSectionName());
        }
        allsubject = subjectBean.getallSubjectsByClass(classes.getClassID());
        int y1= 20;
        int y2 = 20;
        for(j=0;j<allsubject.size();j++){
            JTextField a = new JTextField();
            JTextField b = new JTextField();
            subjectmarksinput.add(a);
            subjectmarksoutof.add(b);
        }
        for(int i =0;i<subjectmarksinput.size();i++){
            subjectBean = allsubject.get(i);
            JLabel subjectname = new JLabel(subjectBean.getSubjectName());
            JLabel outof = new JLabel("Out Of");
            JTextField si = subjectmarksinput.get(i);
            JTextField sout = subjectmarksoutof.get(i);
            subjectname.setBounds(20, y1, 100, 30);
            si.setBounds(130, y2,70, 30);
            outof.setBounds(210, y2, 70, 30);
            sout.setBounds(290, y2,70, 30);
            jPanel3.add(subjectname);
            jPanel3.add(si);
            jPanel3.add(sout);
            jPanel3.add(outof);
            y1=y1+50;
            y2 = y2 + 50;
        }
    }//GEN-LAST:event_class_selectionActionPerformed

    private void section_selectionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_section_selectionActionPerformed
        // TODO add your handling code here:
        allStudents = students.getAllStudentsBySection((String) section_selection.getSelectedItem());
        DefaultTableModel model = (DefaultTableModel)allstudentsbysection.getModel();
        Object[] rowData = new Object[4];
        for(int i=0;i<model.getRowCount();i++){
            model.removeRow(i);
        }
        for(int i =0;i<allStudents.size();i++){
            students = allStudents.get(i);
            rowData[0] = students.getStudentId();
            rowData[1] = students.getFirstname();
            rowData[2] = students.getLastname();
            rowData[3] = students.getFathername();
            model.addRow(rowData);
        }
    }//GEN-LAST:event_section_selectionActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        ViewResult result = new ViewResult();
        result.show();
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jLabel14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel14MouseClicked
        // TODO add your handling code here:
        Home home = new Home();
        home.show();
        dispose();
    }//GEN-LAST:event_jLabel14MouseClicked

    private void exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_exitMouseClicked

    private void addresultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addresultActionPerformed
        // TODO add your handling code here:
        ArrayList<Double> obtainedmarks = new ArrayList<>();
        ArrayList<Double> totalmarks = new ArrayList<>();
        Double sumofobmarks=0.0;
        Double sumoftotalmarks=0.0;
        for(int i=0;i<subjectmarksinput.size();i++){
            JTextField sbmarks = subjectmarksinput.get(i);
            JTextField sbmarksoutof = subjectmarksoutof.get(i);
            sumofobmarks = sumofobmarks + Double.parseDouble(sbmarks.getText());
            sumoftotalmarks = sumoftotalmarks + Double.parseDouble(sbmarksoutof.getText());
            obtainedmarks.add(Double.parseDouble(sbmarks.getText()));
            totalmarks.add(Double.parseDouble(sbmarksoutof.getText()));
        }
        Double Percentage = sumofobmarks/sumoftotalmarks * 100;
        String obmarks = new Gson().toJson(obtainedmarks);
        String Grade;
        String Status;
        if(Percentage >=90 && Percentage <100){
            Grade = "A1";
            Status = "Passes";
            System.out.print(Grade);
        }
        else if(Percentage >=80 && Percentage <90){
            Grade = "A+";
            Status = "Passes";
            System.out.print(Grade);
        }
        else if(Percentage >=80 && Percentage <90){
            Grade = "A+";
            Status = "Passes";
            System.out.print(Grade);
        }
        else if(Percentage >=70 && Percentage <80){
            Grade = "A";
            Status = "Passes";
            System.out.print(Grade);
        }
        else if(Percentage >=60 && Percentage <70){
            Grade = "B";
            Status = "Passes";
            System.out.print(Grade);
        }
        else if(Percentage >=50 && Percentage <60){
            Grade = "C";
            Status = "Passes";
            System.out.print(Grade);
        }
        else if(Percentage >=40 && Percentage <50){
            Grade = "D";
            Status = "Passes";
            System.out.print(Grade);
        }
        else if(Percentage >=33 && Percentage <40){
            Grade = "E";
            Status = "Passes";
            System.out.print(Grade);
        }
        else{
            Grade = "null";
            Status = "Fail";
            System.out.print(Grade);
        }
        TableModel model = allstudentsbysection.getModel();
        int i = allstudentsbysection.getSelectedRow();
        int id = (int) model.getValueAt(i, 0);
        boolean result = db.addResult(obmarks, sumofobmarks, sumoftotalmarks, Percentage, Grade, Status, id);
        if(result){
            JOptionPane.showMessageDialog(this, "result has been added");
        }
        else{
            JOptionPane.showMessageDialog(this, "result has not been added");
        }
    }//GEN-LAST:event_addresultActionPerformed

    private void section_selectionMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_section_selectionMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_section_selectionMouseReleased
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ResultManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ResultManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ResultManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ResultManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ResultManagement().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addresult;
    private javax.swing.JTable allstudentsbysection;
    private javax.swing.JComboBox class_selection;
    private javax.swing.JLabel exit;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox section_selection;
    // End of variables declaration//GEN-END:variables
}
