/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frontend;

import java.awt.Color;
import javax.swing.BorderFactory;
import Backend.ClassBean;
import Backend.SectionBean;
import Backend.StudentBean;
import java.awt.print.PrinterException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import net.proteanit.sql.DbUtils;
/**
 *
 * @author aqibm
 */
public class Students extends javax.swing.JFrame {

    /**
     * Creates new form Students
     */
     ClassBean class1 = new ClassBean();
     ArrayList<ClassBean> allclasses = new ArrayList<>();
     ArrayList<SectionBean> allSections = new ArrayList<>();
     ArrayList<StudentBean> getAllStudents = new ArrayList<>();
     SectionBean sectionBean = new SectionBean();
     StudentBean student = new StudentBean();
     int classId;
     int StudentId;
     Object[] rowdata = new Object[8];
    public Students() {
        initComponents();
        setLocationRelativeTo(null);
        allclasses = class1.getAllClasses();
        for(int i=0;i<allclasses.size();i++){
            class1 = allclasses.get(i);
            System.out.println(class1.getClassName());
            classselection.addItem(class1.getClassName());
        }
        showStudents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        exit = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        Firstname = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        Lastname = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        Contactno = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        Fathername = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        classselection = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        sections_selections = new javax.swing.JComboBox();
        addStudent = new javax.swing.JButton();
        ViewStudent = new javax.swing.JButton();
        updateStudent = new javax.swing.JButton();
        DeleteStudent = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        allStudents = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        Address = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(255, 102, 51));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        exit.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        exit.setForeground(new java.awt.Color(255, 255, 255));
        exit.setText("X");
        exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitMouseClicked(evt);
            }
        });
        jPanel2.add(exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(838, 0, 22, -1));

        jLabel15.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Students");
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 40, -1, -1));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/images/group_52px_1.png"))); // NOI18N
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 90, 100));

        jLabel8.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/images/back.png"))); // NOI18N
        jLabel8.setText("Back");
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 40, -1, -1));

        jLabel1.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel1.setText("Name");

        Firstname.setBorder(BorderFactory.createLineBorder(Color.decode("#e0dad7"),1,true)
        );
        Firstname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FirstnameActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel2.setText("Last Name");

        Lastname.setBorder(BorderFactory.createLineBorder(Color.decode("#e0dad7"),1,true)
        );
        Lastname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LastnameActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel3.setText("Contact No");

        Contactno.setBorder(BorderFactory.createLineBorder(Color.decode("#e0dad7"),1,true)
        );
        Contactno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ContactnoActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel4.setText("Father Name");

        Fathername.setBorder(BorderFactory.createLineBorder(Color.decode("#e0dad7"),1,true)
        );
        Fathername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FathernameActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel5.setText("Class");

        classselection.setBorder(BorderFactory.createLineBorder(Color.decode("#e0dad7"),1,true));
        classselection.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                classselectionActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel6.setText("Section");

        sections_selections.setBorder(BorderFactory.createLineBorder(Color.decode("#e0dad7"),1,true));

        addStudent.setBackground(new java.awt.Color(255, 102, 51));
        addStudent.setForeground(new java.awt.Color(255, 255, 255));
        addStudent.setText("ADD");
        addStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addStudentActionPerformed(evt);
            }
        });

        ViewStudent.setBackground(new java.awt.Color(255, 102, 51));
        ViewStudent.setForeground(new java.awt.Color(255, 255, 255));
        ViewStudent.setText("View");
        ViewStudent.setEnabled(false);
        ViewStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewStudentActionPerformed(evt);
            }
        });

        updateStudent.setBackground(new java.awt.Color(255, 102, 51));
        updateStudent.setForeground(new java.awt.Color(255, 255, 255));
        updateStudent.setText("UPDATE");
        updateStudent.setEnabled(false);
        updateStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateStudentActionPerformed(evt);
            }
        });

        DeleteStudent.setBackground(new java.awt.Color(255, 102, 51));
        DeleteStudent.setForeground(new java.awt.Color(255, 255, 255));
        DeleteStudent.setText("DELETE");
        DeleteStudent.setEnabled(false);
        DeleteStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteStudentActionPerformed(evt);
            }
        });

        allStudents.setBorder(BorderFactory.createLineBorder(Color.decode("#e0dad7"),1,true));
        allStudents.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Firstname", "Lastname", "Fathername", "Address", "ContactNo", "Class", "Section"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        allStudents.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                allStudentsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(allStudents);
        allStudents.getTableHeader().setOpaque(false);
        allStudents.getTableHeader().setBackground(Color.decode("#ff6633"));

        jLabel7.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel7.setText("Address");

        Address.setBorder(BorderFactory.createLineBorder(Color.decode("#e0dad7"),1,true)
        );
        Address.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddressActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(addStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ViewStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(DeleteStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(updateStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(Fathername, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                                    .addComponent(Contactno, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                                    .addComponent(Lastname, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                                    .addComponent(Firstname, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                                    .addComponent(classselection, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(sections_selections, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(Address))
                                .addGap(75, 75, 75)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, 0))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(Firstname, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(Lastname, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(Contactno, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Fathername, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Address, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel6))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(classselection, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(sections_selections, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ViewStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(updateStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DeleteStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(55, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ViewStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewStudentActionPerformed
        // TODO add your handling code here:
        int i = allStudents.getSelectedRow();
        TableModel model = allStudents.getModel();
        ViewStudent viewStudent = new ViewStudent();
        viewStudent.Firstname.setText((String) model.getValueAt(i, 1));
        viewStudent.Lastname.setText((String) model.getValueAt(i, 2));
        viewStudent.Fathername.setText((String) model.getValueAt(i, 3));
        viewStudent.Address.setText((String) model.getValueAt(i, 4));
        viewStudent.ContactNo.setText((String) model.getValueAt(i, 5));
        viewStudent.Class.setText((String) model.getValueAt(i, 6));
        viewStudent.Section.setText((String) model.getValueAt(i, 7));
        viewStudent.show();
        dispose();
    }//GEN-LAST:event_ViewStudentActionPerformed

    private void FathernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FathernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FathernameActionPerformed

    private void ContactnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ContactnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ContactnoActionPerformed

    private void LastnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LastnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LastnameActionPerformed

    private void FirstnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FirstnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FirstnameActionPerformed

    private void AddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AddressActionPerformed

    private void classselectionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_classselectionActionPerformed
        // TODO add your handling code here:
          String classname = classselection.getSelectedItem().toString();
          int indexofclassname = classselection.getSelectedIndex();
          class1 = allclasses.get(indexofclassname);
          classId = class1.getClassID();
          sections_selections.removeAllItems();
          allSections = sectionBean.allSectionsByClass(classId);
          for(int i=0;i<allSections.size();i++){
              sectionBean = allSections.get(i);
              sections_selections.addItem(sectionBean.getSectionName());
          }
//          System.out.println(class1.getClassID());
    }//GEN-LAST:event_classselectionActionPerformed

    private void exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_exitMouseClicked

    private void addStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addStudentActionPerformed
        // TODO add your handling code here:
        String firstname = Firstname.getText();
        String lastname = Lastname.getText();
        String contactno = Contactno.getText();
        String address = Address.getText();
        String fathername = Fathername.getText();
        int ClassId = classId;
        String section = (String) sections_selections.getSelectedItem();
        String message = student.addStudent(firstname, lastname, fathername, address, contactno, ClassId, section);
        JOptionPane.showMessageDialog(this, message);
        int rowcount = allStudents.getRowCount();
        int i = rowcount+1;
        DefaultTableModel model = (DefaultTableModel)allStudents.getModel();
        rowdata[0] = student.getStudentId()+1;
            rowdata[1] = firstname;
            rowdata[2] = lastname;
            rowdata[3] = fathername;
            rowdata[4] = address;
            rowdata[5] = contactno;
            rowdata[6] = classselection.getSelectedItem();
            rowdata[7] = section;
            model.addRow(rowdata);
    }//GEN-LAST:event_addStudentActionPerformed

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        // TODO add your handling code here:
        Home home = new Home();
        home.show();
        dispose();
    }//GEN-LAST:event_jLabel8MouseClicked

    private void allStudentsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_allStudentsMouseClicked
        // TODO add your handling code here:
        int i = allStudents.getSelectedRow();
        TableModel model = allStudents.getModel();
        StudentId = (int) model.getValueAt(i, 0);
        Firstname.setText(model.getValueAt(i, 1).toString());
        Lastname.setText(model.getValueAt(i, 2).toString());
        Fathername.setText(model.getValueAt(i, 3).toString());
        Address.setText(model.getValueAt(i, 4).toString());
        Contactno.setText(model.getValueAt(i, 5).toString());
        classselection.setSelectedItem(model.getValueAt(i, 6).toString());
        sections_selections.setSelectedItem(model.getValueAt(i, 7).toString());
        updateStudent.setEnabled(true);
        DeleteStudent.setEnabled(true);
        ViewStudent.setEnabled(true);
    }//GEN-LAST:event_allStudentsMouseClicked

    private void updateStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateStudentActionPerformed
        // TODO add your handling code here:
        int i = allStudents.getSelectedRow();
        String firstname = Firstname.getText();
        String lastname = Lastname.getText();
        String fathername = Fathername.getText();
        String address = Address.getText();
        String contactno = Contactno.getText();
        int classid = classId;
        String Section = (String) sections_selections.getSelectedItem();
        String message = student.updateStudent(StudentId, firstname, lastname, fathername, contactno, address, Section, classid);
        JOptionPane.showMessageDialog(this, message);
        DefaultTableModel model = (DefaultTableModel)allStudents.getModel();
//        rowdata[0] = student.getStudentId();
//            rowdata[1] = firstname;
//            rowdata[2] = lastname;
//            rowdata[3] = fathername;
//            rowdata[4] = address;
//            rowdata[5] = contactno;
//            rowdata[6] = classselection.getSelectedItem();
//            rowdata[7] = Section;
        model.setValueAt(model.getValueAt(i, 0), i, 0);
        model.setValueAt(firstname, i, 1);
        model.setValueAt(lastname, i, 2);
        model.setValueAt(fathername, i, 3);
        model.setValueAt(address, i, 4);
        model.setValueAt(contactno, i, 5);
        model.setValueAt(classselection.getSelectedItem(), i, 6);
        model.setValueAt(sections_selections.getSelectedItem(), i, 7);
    }//GEN-LAST:event_updateStudentActionPerformed

    private void DeleteStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteStudentActionPerformed
        // TODO add your handling code here:
        int i = allStudents.getSelectedRow();
        int respond = JOptionPane.showConfirmDialog(this, "Are you sure you want to delete this student?", "Confirm",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
        if(respond == JOptionPane.YES_OPTION){
        TableModel model = allStudents.getModel();
        int id = (int) model.getValueAt(i, 0);
        String message = student.deleteStudent(id);
        JOptionPane.showMessageDialog(this, message);
        int k = allStudents.getSelectedRow();
        DefaultTableModel model2 = (DefaultTableModel)allStudents.getModel();
        model2.removeRow(i);
        }
        
    }//GEN-LAST:event_DeleteStudentActionPerformed
    void showStudents(){
        getAllStudents = student.getAllStudents();
        DefaultTableModel model = (DefaultTableModel)allStudents.getModel();
        for(int i = 0;i<getAllStudents.size();i++){
            student = getAllStudents.get(i);
            rowdata[0] = student.getStudentId();
            rowdata[1] = student.getFirstname();
            rowdata[2] = student.getLastname();
            rowdata[3] = student.getFathername();
            rowdata[4] = student.getAddress();
            rowdata[5] = student.getContactNo();
            rowdata[6] = student.getClassName();
            rowdata[7] = student.getSection();
            model.addRow(rowdata);
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Students.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Students.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Students.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Students.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
//        for(int i=0;i<allclasses.size();i++){
//            class1 = allclasses.get(i);
//            System.out.println(class1.getClassName());
//        }
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Students().setVisible(true);
            }
        });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Address;
    private javax.swing.JTextField Contactno;
    private javax.swing.JButton DeleteStudent;
    private javax.swing.JTextField Fathername;
    private javax.swing.JTextField Firstname;
    private javax.swing.JTextField Lastname;
    private javax.swing.JButton ViewStudent;
    private javax.swing.JButton addStudent;
    private javax.swing.JTable allStudents;
    private javax.swing.JComboBox classselection;
    private javax.swing.JLabel exit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox sections_selections;
    private javax.swing.JButton updateStudent;
    // End of variables declaration//GEN-END:variables
}
