/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frontend;

import java.awt.Color;
import javax.swing.BorderFactory;
import Backend.*;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author aqibm
 */
public class Teacher extends javax.swing.JFrame {

    /**
     * Creates new form Students
     */
    TeacherBean teacher = new TeacherBean();
    ArrayList<TeacherBean> getallTeachers = new ArrayList<>();
    int TeacherId;
    Object[] rowdata = new Object[6];
    public Teacher() {
        initComponents();
        showteachers();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        exit = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        Firstname = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        Lastname = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        Qualification = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        ContactNo = new javax.swing.JTextField();
        addTeacher = new javax.swing.JButton();
        ViewTeacher = new javax.swing.JButton();
        updateTeacher = new javax.swing.JButton();
        deleteTeacher = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        allteachers = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        CNIC = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(255, 102, 51));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        exit.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        exit.setForeground(new java.awt.Color(255, 255, 255));
        exit.setText("X");
        exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitMouseClicked(evt);
            }
        });
        jPanel2.add(exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(838, 0, 22, -1));

        jLabel15.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Teacher Management");
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 40, -1, -1));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/images/teacher_white_48px.png"))); // NOI18N
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 90, 100));

        jLabel9.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/images/back.png"))); // NOI18N
        jLabel9.setText("Back");
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 40, -1, -1));

        jLabel1.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel1.setText("First Name");

        Firstname.setBorder(BorderFactory.createLineBorder(Color.decode("#e0dad7"),1,true)
        );
        Firstname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FirstnameActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel2.setText("Last Name");

        Lastname.setBorder(BorderFactory.createLineBorder(Color.decode("#e0dad7"),1,true)
        );
        Lastname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LastnameActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel3.setText("Qualification");

        Qualification.setBorder(BorderFactory.createLineBorder(Color.decode("#e0dad7"),1,true)
        );
        Qualification.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QualificationActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel4.setText("Contact No");

        ContactNo.setBorder(BorderFactory.createLineBorder(Color.decode("#e0dad7"),1,true)
        );
        ContactNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ContactNoActionPerformed(evt);
            }
        });

        addTeacher.setBackground(new java.awt.Color(255, 102, 51));
        addTeacher.setForeground(new java.awt.Color(255, 255, 255));
        addTeacher.setText("ADD");
        addTeacher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addTeacherActionPerformed(evt);
            }
        });

        ViewTeacher.setBackground(new java.awt.Color(255, 102, 51));
        ViewTeacher.setForeground(new java.awt.Color(255, 255, 255));
        ViewTeacher.setText("View");
        ViewTeacher.setEnabled(false);
        ViewTeacher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewTeacherActionPerformed(evt);
            }
        });

        updateTeacher.setBackground(new java.awt.Color(255, 102, 51));
        updateTeacher.setForeground(new java.awt.Color(255, 255, 255));
        updateTeacher.setText("UPDATE");
        updateTeacher.setEnabled(false);
        updateTeacher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateTeacherActionPerformed(evt);
            }
        });

        deleteTeacher.setBackground(new java.awt.Color(255, 102, 51));
        deleteTeacher.setForeground(new java.awt.Color(255, 255, 255));
        deleteTeacher.setText("DELETE");
        deleteTeacher.setEnabled(false);
        deleteTeacher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteTeacherActionPerformed(evt);
            }
        });

        allteachers.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Name", "Lastname", "Qualification", "ContactNo", "CNIC"
            }
        ));
        allteachers.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                allteachersMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(allteachers);

        jLabel6.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel6.setText("CNIC");

        CNIC.setBorder(BorderFactory.createLineBorder(Color.decode("#e0dad7"),1,true)
        );
        CNIC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CNICActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(addTeacher, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ViewTeacher, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(deleteTeacher, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(updateTeacher, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(ContactNo, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                            .addComponent(Qualification)
                            .addComponent(Lastname)
                            .addComponent(Firstname)
                            .addComponent(CNIC))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 396, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(Firstname, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(Lastname, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(Qualification, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ContactNo, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CNIC, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(addTeacher, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ViewTeacher, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(updateTeacher, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(deleteTeacher, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(181, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ViewTeacherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewTeacherActionPerformed
        // TODO add your handling code here:
        int i = allteachers.getSelectedRow();
        TableModel model = allteachers.getModel();
        ViewTeacher viewTeacher = new ViewTeacher();
        viewTeacher.Firstname.setText((String) model.getValueAt(i, 1));
        viewTeacher.Lastname.setText((String) model.getValueAt(i, 2));
        viewTeacher.Qualification.setText((String) model.getValueAt(i, 3));
        viewTeacher.ContactNo.setText((String) model.getValueAt(i, 4));
        viewTeacher.CNIC.setText((String) model.getValueAt(i, 5));
        viewTeacher.show();
        dispose();
    }//GEN-LAST:event_ViewTeacherActionPerformed

    private void ContactNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ContactNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ContactNoActionPerformed

    private void QualificationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QualificationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_QualificationActionPerformed

    private void LastnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LastnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LastnameActionPerformed

    private void FirstnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FirstnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FirstnameActionPerformed

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        // TODO add your handling code here:
        Home home = new Home();
        home.show();
        dispose();
    }//GEN-LAST:event_jLabel9MouseClicked

    private void CNICActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CNICActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CNICActionPerformed

    private void addTeacherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addTeacherActionPerformed
        // TODO add your handling code here:
        String firstname = Firstname.getText();
        String lastname = Lastname.getText();
        String qualification = Qualification.getText();
        String contactno = ContactNo.getText();
        String cnic = CNIC.getText();
        String message = teacher.addTeacher(firstname, lastname, qualification, contactno, cnic);
        JOptionPane.showMessageDialog(this, message);
        DefaultTableModel model = (DefaultTableModel)allteachers.getModel();
        rowdata[0] = teacher.getTeacherId() +1;
        rowdata[1] = firstname;
        rowdata[2] = lastname;
        rowdata[3] = qualification;
        rowdata[4] = contactno;
        rowdata[5] = cnic;
        model.addRow(rowdata);
    }//GEN-LAST:event_addTeacherActionPerformed

    private void allteachersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_allteachersMouseClicked
        // TODO add your handling code here:
        int i = allteachers.getSelectedRow();
        TableModel model = allteachers.getModel();
        TeacherId = (int)model.getValueAt(i, 0);
        Firstname.setText((String) model.getValueAt(i, 1));
        Lastname.setText((String) model.getValueAt(i, 2));
        Qualification.setText((String) model.getValueAt(i, 3));
        ContactNo.setText((String) model.getValueAt(i, 4));
        CNIC.setText((String) model.getValueAt(i, 5));
        deleteTeacher.setEnabled(true);
        updateTeacher.setEnabled(true);
        ViewTeacher.setEnabled(true);
    }//GEN-LAST:event_allteachersMouseClicked

    private void updateTeacherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateTeacherActionPerformed
        // TODO add your handling code here:
        String firstname = Firstname.getText();
        String lastname = Lastname.getText();
        String qualification = Qualification.getText();
        String contactno = ContactNo.getText();
        String cnic = CNIC.getText();
        String message = teacher.updateTeacher(TeacherId, firstname, lastname, qualification, contactno, cnic);
        JOptionPane.showMessageDialog(this, message);
        int i = allteachers.getSelectedRow();
        DefaultTableModel model = (DefaultTableModel)allteachers.getModel();
        model.setValueAt(model.getValueAt(i, 0), i, 0);
        model.setValueAt(firstname, i, 1);
        model.setValueAt(lastname, i, 2);
        model.setValueAt(qualification, i, 3);
        model.setValueAt(contactno, i, 4);
        model.setValueAt(cnic, i, 5);
    }//GEN-LAST:event_updateTeacherActionPerformed

    private void deleteTeacherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteTeacherActionPerformed
        // TODO add your handling code here:
        int respond = JOptionPane.showConfirmDialog(this, "Are you sure you want to delete this student?", "Confirm",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
        if(respond == JOptionPane.YES_OPTION){
            int i = allteachers.getSelectedRow();
        TableModel model = allteachers.getModel();
        int id = (int)model.getValueAt(i, 0);
        String message = teacher.deleteTeacher(id);
        JOptionPane.showMessageDialog(this, message);
                int k = allteachers.getSelectedRow();
         getallTeachers.remove(k);
        }
    }//GEN-LAST:event_deleteTeacherActionPerformed

    private void exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_exitMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Students.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Students.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Students.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Students.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Teacher().setVisible(true);
            }
        });
    }
    void showteachers(){
       getallTeachers = teacher.getAllTeachers();
        Object[] rowdata = new Object[6];
        DefaultTableModel model = (DefaultTableModel)allteachers.getModel();
//        for(int j=0;j<allteachers.getRowCount();j++){
//            model.removeRow(j);
//        }
        for(int i = 0;i<getallTeachers.size();i++){
            teacher = getallTeachers.get(i);
            rowdata[0] = teacher.getTeacherId();
            rowdata[1] = teacher.getFirstname();
            rowdata[2] = teacher.getLastname();
            rowdata[3] = teacher.getQualification();
            rowdata[4] = teacher.getContactNo();
            rowdata[5] = teacher.getCNIC();
            model.addRow(rowdata);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CNIC;
    private javax.swing.JTextField ContactNo;
    private javax.swing.JTextField Firstname;
    private javax.swing.JTextField Lastname;
    private javax.swing.JTextField Qualification;
    private javax.swing.JButton ViewTeacher;
    private javax.swing.JButton addTeacher;
    private javax.swing.JTable allteachers;
    private javax.swing.JButton deleteTeacher;
    private javax.swing.JLabel exit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton updateTeacher;
    // End of variables declaration//GEN-END:variables
}
